version: "2"

services:
  main:
    build: .
    ports:
     - "8080:8080"
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      PORT: "8080"
      RACK_ENV: production
      TWITTER_PUBLIC_TOKEN: ${TWITTER_PUBLIC_TOKEN}
      AUTH_TOKEN: ${AUTH_TOKEN}
      CT0: ${CT0}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      # LETSENCRYPT_TEST: "true"
    restart: unless-stopped
    networks:
      - default
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
